server:
  port:8080
spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
          - id: user-service
            uri: http://user-service:8081
            predicates:
              - Path=/api/user-service/**

          - id: subscription-service
            uri: http://subscription-service:8082
            predicates:
                  - Path=/api/subscription-service/**